apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
      - name: volume-storage
        mountPath: /usr/share/nginx/html
      
  volumes:
   - name: volume-storage 
     emptyDir: {}