apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
      - mountPath: /usr/share/nginx/html
        name: persistent-storage
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: nginx-pvc