apiVersion: apps/v1
kind: Deployment
metadata:
  name: full-stack-app-deployment
  labels:
    app: full-stack-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: full-stack-app
  template:
    metadata:
      labels:
        app: full-stack-app
    spec:
      containers:
        - name: full-stack-app
          image: nahid0002/node-full-stack-app:latest
          ports:
            - containerPort: 4000
          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: full-stack-app-svc
spec:
  selector:
    app: full-stack-app
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: NodePort # Change this according to your environment (NodePort, LoadBalancer, etc.)