apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJTm9kb0FRZVJLTUF3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRBNE1qa3hPVEU1TURaYUZ3MHpOREE0TWpjeE9USTBNRFphTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURvZVozUXdVRi9sZythamRqOGU4MXlPNVFURlRvcjFJRktkMWtWQ252VUZjRlR3QTVsbnkwMEFlMU8KYzMvMVNiTlBWendldFFRRTJXdjNPSGlMUUEwaTl6VFlsUy9VSGlEeEVDOVozeHRNOHdGR1oySjFVTXJlRnV2ZQpqbzVYcG10MGJ1aTBCWnZGZXNJTmk0cTZFUlliSmRYTW82UWdzS3plQTBTblIyUnJNZXV4NkFwSS8reE95OEcwCngydEY5eDBYQmNFSVZGeVNhTmN1SXNvQmt6NkVzbldOQVpvZjFkb1ZxSU4ySHQrbEFiM1ZZWXBydlFZWEhNRnQKZlk5UnlNWWIzTkxTMEMxTzIwbmZmRTVQWlVtUUwzTGw0cm54Y2hHcW1TVUtVNmxGOHd2SUdDd01Ld0QzTHplMAorS01XcWpnZ1planNhQ2Z1dmZ0K3kxMWFxWC9kQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJRSTdraFFaWEhjZzhoME9YbmZtZzhOQkE1aFJUQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRRGxJamw5bHczUAo1VUpSdC9WUWtKL2RXdFJucE5LNnRBN0VwYnRJSGx0Wk9sSVNUT1N4b0tpVFhhV0JHKzNLbzd5SXJnOThYWEFXCkpaY3RiSS9pMU45TGpxOVZhV2FBM2FCaUVoU0JTQXpTRmVPTTEwVjREOEEySTRtQ2t1MGlUUDFwZGpOQjVFWTMKaGJXcnRmMVBvckFjZHFRcGMwK2RwcmpaZHdoWGVZdUI4MUJJeW04Zm4yQWZPN0sxYmhoek1pNFJObGt5UlkwbgpLcEQ2NER0cUtyVHN0aXFUN0Z5N2czZDRCdFBTMGtKWStlMHczdFJPcmMySDd1SFZYd0kyZEZTWE9pOGdGUEpLCm1oZU8rWWtBRmN1WUVxMVdUZW9Pb08rUGZxektCcE4vVTJPeWRNamFnd0N3aS9uQjFkbUxwbXRVcXpFRjR4S08KM1FGMUhEeFlCY2ZWCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server:  https://172.31.91.187:6443
  name:  kubernetes
contexts:
- context:
    cluster: Kubernetes
    user: admin
  name: admin-context
current-context: admin-context
kind: Config
preferences: {}
users:
- name:  admin
  users:
    token: <admn-token> #replace with generate token  
